drivers: net: broadcom: updates from bcmdhd_101_24 driver
Fixes error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]
        STATIC_ASSERT(OFFSETOF(wl_pfn_subnet_info_v1_t, SSID) ==
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/net/wireless/broadcom/bcmdhd_101_18/dhd_pno.c:3093:2: error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]
 3093 |         STATIC_ASSERT(OFFSETOF(wl_pfn_subnet_info_v1_t, SSID) ==
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3094 |                       OFFSETOF(wl_pfn_subnet_info_v2_t, u.SSID));
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~